# Лаборатораня работа №1
## Выполнил студент группы БСТ1902 Птушкин А.Н.

### Задание №1
Вывести "Hello, World"

In [2]:
print("Hello, World!")


Hello, World!


### Задание №2
Написать генератор случайных многомерных матриц

In [3]:
import numpy
import random

M=50
N=50
min_limit=-250
max_limit=1016
    
#Ввод значений
print("_______________________________________________________________________________")
print("\nГенерация случайных матриц размера MxN со значениями от min_limit до max_limit.")
print("_______________________________________________________________________________")

strM=input("\n\nВведите M: ")
if len(strM)>0: M=int(strM)
    
strN=input("Введите N: ")
if len(strN)>0: N=int(strN)
    
#Минимальный элемент не может быть больше максимального
while True:
        
    strMin_limit=input("Введите минимальное значение: ")
    if len(strMin_limit)>0: min_limit=int(strMin_limit)

    strMax_limit=input("Введите максимальное значение: ")
    if len(strMax_limit)>0: max_limit=int(strMax_limit)
            
    #Условие выхода из цикла
    if (min_limit<=max_limit): break
    else: print("\nМинимальный элемент не может быть больше максимального, повторите попытку\n")

print("\n\n_______________________________________________________________________________")


#Создание матрицы 
array=numpy.zeros((M,N))
    
#Заполнение матрицы
for i in range(M):
    for j in range(N):
        array[i][j]=random.randint(int(min_limit), int(max_limit))


#Вывод
print("\n\nМатрица сгенерирована:\n")
print(array)
print("\n\n_______________________________________________________________________________")
        



_______________________________________________________________________________

Генерация случайных матриц размера MxN со значениями от min_limit до max_limit.
_______________________________________________________________________________


Введите M: 10
Введите N: 9
Введите минимальное значение: 7
Введите максимальное значение: 100


_______________________________________________________________________________


Матрица сгенерирована:

[[ 29.  41.  78.  10.  17.  76.  87.  22.  48.]
 [ 88.  80. 100.  44.  74.  36.  11.  62.  39.]
 [  8.  31.  79.  95.  11.  97.  74.  25.  46.]
 [ 45.  26.  75.  47.  41.  89.  70.  94.  32.]
 [ 30.  94.  93.  61.  25.  68.  54.  51.  69.]
 [ 55.  26.  56.  96.  81.  39.  22.  74.  90.]
 [ 12.  53.  43.  30.  50.  72.  44.  33.  25.]
 [ 23.  15.  78.  73.  41.  33.  40.  68.  33.]
 [ 10.  78.  59.  78.  84.  35.   7.  44.  15.]
 [ 78.  80.  19.  73.  28.  62.  11.  90.  14.]]


________________________________________________________________________

### Задание №3
Методы сортировки

#### Сортировка выборкой

In [4]:
def Selection_Sort(old_array):
    new_array=old_array.copy()
    for i in range(M):
        for j in range(N-1):
            min=j
            for h in range (j+1,N):
                if (new_array[i][h]<new_array[i][min]):
                    min=h
            temp=new_array[i][j]
            new_array[i][j]=new_array[i][min]
            new_array[i][min]=temp
    return new_array

#### Сортировка вставкой

In [5]:
def Insertion_Sort(old_array):
    new_array=old_array.copy()
    for i in range(M):
        for j in range(1,N):
            temp=new_array[i][j]
            index=j
            while (temp<new_array[i][index-1]) and (index>0):
                new_array[i][index]=new_array[i][index-1]
                index-=1
            new_array[i][index]=temp
    return new_array

#### Сортировка обменом

In [13]:
def Bubble_Sort(old_array):
    new_array=old_array.copy()
    for i in range(M):
        for j in range(N):
            for h in range(N-j-1):
                if new_array[i][h+1]<new_array[i][h]:
                    new_array[i][h],new_array[i][h+1]=new_array[i][h+1],new_array[i][h]
    return new_array

#### Сортировка Шелла

In [7]:
def Shell_Sort(old_array):
    new_array=old_array.copy()
    for i in range(M):
        d=int(N/2)
        while d>0:
            for j in range(N):
                for h in range(int(j+d),N,d):
                    if new_array[i][j]>new_array[i][h]:
                        temp=new_array[i][j]
                        new_array[i][j]=new_array[i][h]
                        new_array[i][h]=temp
            
            d=int(d/2)
    return new_array

#### Турнирная сортировка

In [22]:
def tournament_sort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2
    
    for i, v in enumerate(arr):
        tree[index + i] = (i, v)
    
    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1) 
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

#### Быстрая сортировка

In [18]:
def Quicksort_Start(old_array):
    new_array=old_array.copy()
    for i in range(M):
        Quicksort(0,M-2,new_array,i)
    return new_array

def Quicksort(_first, _last, _array, row):
    first=int(_first)
    last=int(_last)
    middle=int((first+last)/2)
    
    while (first<last):
        
        while( _array[row][first] < _array[row][middle]): 
            first+=1
        while( _array[row][last] > _array[row][middle]):
            last-=1
        if(first<=last):
            temp=_array[row][first]
            _array[row][first]=_array[row][last]
            _array[row][last]=temp
            first+=1
            last-=1
    
    if(_first<last):
        Quicksort(_first,last,_array,row)
    if(first<_last):
        Quicksort(first,_last,_array,row)

#### Пирамидальная сортировка

In [21]:
# Python program for implementation of heap Sort

# To heapify subtree rooted at index i.
# n is size of heap


def heapify(arr, n, i):
	largest = i # Initialize largest as root
	l = 2 * i + 1	 # left = 2*i + 1
	r = 2 * i + 2	 # right = 2*i + 2

	# See if left child of root exists and is
	# greater than root
	if l < n and arr[largest] < arr[l]:
		largest = l

	# See if right child of root exists and is
	# greater than root
	if r < n and arr[largest] < arr[r]:
		largest = r

	# Change root, if needed
	if largest != i:
		arr[i], arr[largest] = arr[largest], arr[i] # swap

		# Heapify the root.
		heapify(arr, n, largest)

# The main function to sort an array of given size


def heapSort(arr):
	n = len(arr)

	# Build a maxheap.
	for i in range(n//2 - 1, -1, -1):
		heapify(arr, n, i)

	# One by one extract elements
	for i in range(n-1, 0, -1):
		arr[i], arr[0] = arr[0], arr[i] # swap
		heapify(arr, i, 0)


# Driver code
arr = [12, 11, 13, 5, 6, 7]
heapSort(arr)
n = len(arr)
print("Sorted array is")
for i in range(n):
	print("%d" % arr[i]),
# This code is contributed by Mohit Kumra



Sorted array is
5
6
7
11
12
13


### Вызов функций

In [19]:
print("Исходная матрица:\n\n",array,"\n=====================")
print("Сортировка выборкой:\n\n",Selection_Sort(array),"\n=====================")
print("Сортировка вставкой:\n\n",Insertion_Sort(array),"\n=====================")
print("Сортировка обменом:\n\n",Bubble_Sort(array),"\n=====================")
print("Сортировка Шелла:\n\n",Shell_Sort(array),"\n=====================")
print("Быстрая сортировка:\n\n",Quicksort_Start(array),"\n=====================")

Исходная матрица:

 [[ 29.  41.  78.  10.  17.  76.  87.  22.  48.]
 [ 88.  80. 100.  44.  74.  36.  11.  62.  39.]
 [  8.  31.  79.  95.  11.  97.  74.  25.  46.]
 [ 45.  26.  75.  47.  41.  89.  70.  94.  32.]
 [ 30.  94.  93.  61.  25.  68.  54.  51.  69.]
 [ 55.  26.  56.  96.  81.  39.  22.  74.  90.]
 [ 12.  53.  43.  30.  50.  72.  44.  33.  25.]
 [ 23.  15.  78.  73.  41.  33.  40.  68.  33.]
 [ 10.  78.  59.  78.  84.  35.   7.  44.  15.]
 [ 78.  80.  19.  73.  28.  62.  11.  90.  14.]] 
Сортировка выборкой:

 [[ 10.  17.  22.  29.  41.  48.  76.  78.  87.]
 [ 11.  36.  39.  44.  62.  74.  80.  88. 100.]
 [  8.  11.  25.  31.  46.  74.  79.  95.  97.]
 [ 26.  32.  41.  45.  47.  70.  75.  89.  94.]
 [ 25.  30.  51.  54.  61.  68.  69.  93.  94.]
 [ 22.  26.  39.  55.  56.  74.  81.  90.  96.]
 [ 12.  25.  30.  33.  43.  44.  50.  53.  72.]
 [ 15.  23.  33.  33.  40.  41.  68.  73.  78.]
 [  7.  10.  15.  35.  44.  59.  78.  78.  84.]
 [ 11.  14.  19.  28.  62.  73.  78.  80.  